server:
  port: 3000

spring:
  application:
    name: greeting-v2

eureka:

  instance:
    prefer-ip-address: true


feign:
  hystrix:
    enabled: true

management:
    endpoint:
      metrics:
        enabled: true
    endpoints:
      web:
        exposure:
          include:
            - "*"
