server:
  port: 8080



spring:

  data:
    mongodb:
      database: testDB
      uri: mongodb+srv://username:password@cluster0.5xuvr.mongodb.net/testDB?retryWrites=true&w=majority

  jpa:
#  don't use this in production
    generate-ddl: true
    hibernate:
      ddl-auto: update
#  h2:
#    console:
#      enabled: true
  datasource:
    username: training
    password: 1234
#    url: jdbc:h2:mem:itemDB
    url: jdbc:mysql://localhost:3306/training?serverTimezone=UTC

com:
  aspire:
    training:
      db:
        mongo:
          enabled: true
        rds:
          enabled: false
        in-memory:
          enabled: false
      error-msgs:
        ItemNotFoundException:
          errorCode: 1
          restStatus: 404
          msgs:
            AR: "العنصر المطلوب غير موجود"
            ENG: "Item Not Found"
